// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftdzybltzculfkmvnjax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZHp5Ymx0emN1bGZrbXZuamF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzI0NDQsImV4cCI6MjA3MTc0ODQ0NH0.VR7dOOmJ9mi5eSGca6YSdVadUfp5Gg02TqOrWKdNcMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});